### ISSUE TITLE
Timestamp.from_iso8601 fails to parse JSON timestamp

### ISSUE THREAD

**Issue by bmario** [metricq/metricq-python#9] opened 2020-06-23 15:19 UTC
The C++ agents return in the `discover` RPC response iso timestamps, however, these cannot be parsed.

For example: `2020-06-23T04:00:00.655214846+0200`

There are two issues:

- the nanosecond fraction isn't supported. `%f` is only in microsecond resolution
- the timezone modifier isn't supported

If only computer scientists had invented an automated procedure to check the implementation of code. 😞

**Comment by bmario** [comment] 2020-06-23 15:25
For your convenience:
- https://docs.python.org/3.7/library/datetime.html#strftime-and-strptime-behavior
- https://en.cppreference.com/w/cpp/chrono/c/strftime

Note: the `%f` in the C++ interface is implemented here: https://github.com/metricq/metricq-cpp/blob/master/src/chrono.cpp#L44

**Comment by tilsche** [comment] 2020-06-24 07:14
For uptime, we don't need nanoseconds, so I guess we can use something conforming there. I suppose this issue motivates using option 2 for #7.

**Comment by tilsche** [comment] 2021-03-03 12:29
Note that dateutil.parser.fromiso does 

> For uptime, we don't need nanoseconds, so I guess we can use something conforming there. I suppose this issue motivates using option 2 for #7.

I just checked, yes dateutil does parse the given example (truncating to microseconds). Given that we will probably go with that, I close this as duplicate of #7.

**Closed by tilsche** 2021-03-03 12:29 UTC
Labels: bug
